In [1]:
from ultralytics import YOLO
model = YOLO('./runs/segment/arvore/weights/best.pt')
model.predict(source="./datasets/treeDataset/test/images/IMG_20230515_110505_2_jpg.rf.3ed88a390de5777d8011da13d39705c3.jpg", show=True)


image 1/1 /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/datasets/treeDataset/test/images/IMG_20230515_110505_2_jpg.rf.3ed88a390de5777d8011da13d39705c3.jpg: 640x640 5 Oranges, 1 TreeTop, 1 Trunk, 8.6ms
Speed: 3.0ms preprocess, 8.6ms inference, 9.7ms postprocess per image at shape (1, 3, 640, 640)


[ultralytics.yolo.engine.results.Results object with attributes:
 
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes', 'masks']
 masks: ultralytics.yolo.engine.results.Masks object
 names: {0: 'Orange', 1: 'TreeTop', 2: 'Trunk'}
 orig_img: array([[[228, 226, 225],
         [232, 230, 229],
         [228, 226, 225],
         ...,
         [ 85, 128, 145],
         [ 85, 128, 145],
         [ 84, 127, 144]],
 
        [[203, 201, 200],
         [209, 207, 206],
         [210, 208, 207],
         ...,
         [ 86, 129, 146],
         [ 86, 129, 146],
         [ 85, 128, 145]],
 
        [[215, 213, 212],
         [217, 215, 214],
         [213, 211, 210],
         ...,
         [ 87, 130, 147],
         [ 87, 130, 147],
         [ 87, 130, 147]],
 
        ...,
 
        [[ 46,  84,  88],
         [ 53,  91,  95],
         [ 47,  84,  88],
         ...,
         [  2,  11,  20],
         [  4,  11,  20],
         [  7,  12,  21]],
 
        [[ 23,  64,

: 

In [1]:
from ultralytics import YOLO
model = YOLO('./runs/segment/tomate/weights/best.pt')
results = model.predict(source="./output.mp4", show=True)
# for i, result in enumerate(esults):
#     boxes = result.boxes
#     for box in boxes:
#         xyxy = box.xyxy[0] 



    WARNING ⚠️ stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.

    Usage:
        results = model(source=..., stream=True)  # generator of Results objects
        for r in results:
            boxes = r.boxes  # Boxes object for bbox outputs
            masks = r.masks  # Masks object for segment masks outputs
            probs = r.probs  # Class probabilities for classification outputs



KeyboardInterrupt: 

: 

In [1]:
import torch
torch.cuda.is_available()

True

In [1]:
from ultralytics.yolo.engine.model import YOLO


model = YOLO('./runs/segment/tomate/weights/best.pt')
model.to('cuda')

# force to run on CPU by using device flag
results = model.predict(source="./output.mp4", stream=True, show=True)
for i, result in enumerate(results):
    boxes = result.boxes
    # masks = result.masks
    print(f"result: {result}")
    for box in boxes:
        xyxy = box.xyxy[0] 
        print("xyxy: ", xyxy)
    # for mask in masks:
    #     print("mask: ", mask)


video 1/1 (1/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 71.1ms
video 1/1 (2/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 31 Green-Tomatos, 12.0ms
video 1/1 (3/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 30 Green-Tomatos, 11.9ms
video 1/1 (4/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 27 Green-Tomatos, 11.1ms
video 1/1 (5/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 28 Green-Tomatos, 11.2ms
video 1/1 (6/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 31 Green-Tomatos, 11.1ms
video 1/1 (7/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 28 Green-Tomatos, 11.4ms


result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[228, 212, 217],
        [242, 226, 231],
        [254, 241, 245],
        ...,
        [ 67,  71,  73],
        [ 71,  75,  77],
        [ 74,  78,  80]],

       [[208, 192, 197],
        [239, 223, 228],
        [255, 248, 252],
        ...,
        [ 68,  72,  74],
        [ 71,  75,  77],
        [ 74,  78,  80]],

       [[209, 188, 194],
        [230, 209, 215],
        [251, 233, 238],
        ...,
        [ 69,  73,  75],
        [ 73,  77,  79],
        [ 75,  79,  81]],

       ...,

       [[ 54,  57,  70],
        [ 60,  63,  76],
        [ 65,  68,  81],
        ...,
        [123, 116, 127],
        [124, 117, 128],
        [124, 117, 128]],

       [[ 54,  57,  70],
        [ 61,  64,  77],
        [ 68,  71,  84

video 1/1 (8/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 35 Green-Tomatos, 9.9ms
video 1/1 (9/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 11.3ms
video 1/1 (10/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 27 Green-Tomatos, 12.6ms
video 1/1 (11/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 30 Green-Tomatos, 11.4ms
video 1/1 (12/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 12.4ms


result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[ 67,  86,  97],
        [ 67,  86,  97],
        [ 68,  88,  95],
        ...,
        [ 85, 111, 114],
        [ 85, 111, 114],
        [ 85, 111, 114]],

       [[ 66,  85,  96],
        [ 66,  85,  96],
        [ 66,  86,  93],
        ...,
        [ 85, 111, 114],
        [ 84, 110, 113],
        [ 84, 110, 113]],

       [[ 68,  86,  93],
        [ 68,  86,  93],
        [ 67,  85,  92],
        ...,
        [ 98, 114, 121],
        [ 98, 114, 121],
        [ 97, 113, 120]],

       ...,

       [[ 79,  88,  94],
        [ 77,  86,  92],
        [ 79,  88,  94],
        ...,
        [ 43,  41,  46],
        [ 44,  42,  47],
        [ 46,  44,  49]],

       [[ 79,  88,  94],
        [ 83,  92,  98],
        [ 79,  88,  94

video 1/1 (13/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 30 Green-Tomatos, 11.7ms
video 1/1 (14/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 30 Green-Tomatos, 10.9ms
video 1/1 (15/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 31 Green-Tomatos, 12.4ms
video 1/1 (16/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 30 Green-Tomatos, 11.4ms
video 1/1 (17/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 27 Green-Tomatos, 11.0ms
video 1/1 (18/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 11.0ms
video 1/1 (19/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 11.2ms


tensor([592.5573,   5.8647, 649.2047,  48.0053], device='cuda:0')
xyxy:  tensor([277.6216, 436.3239, 311.8442, 466.5177], device='cuda:0')
result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[188, 166, 168],
        [183, 161, 163],
        [183, 159, 163],
        ...,
        [ 80,  85,  83],
        [ 80,  85,  83],
        [ 81,  86,  84]],

       [[186, 164, 166],
        [185, 163, 165],
        [185, 161, 165],
        ...,
        [ 78,  83,  81],
        [ 80,  85,  83],
        [ 81,  86,  84]],

       [[190, 166, 168],
        [192, 168, 170],
        [194, 167, 172],
        ...,
        [ 78,  83,  81],
        [ 80,  85,  83],
        [ 81,  86,  84]],

       ...,

       [[123, 126, 131],
        [119, 122, 127],
        [120, 121, 126],
        ...,
        [1

video 1/1 (20/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 28 Green-Tomatos, 10.8ms
video 1/1 (21/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 27 Green-Tomatos, 11.6ms
video 1/1 (22/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 27 Green-Tomatos, 12.1ms
video 1/1 (23/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 11.5ms
video 1/1 (24/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 28 Green-Tomatos, 11.3ms
video 1/1 (25/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 10.9ms
video 1/1 (26/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 32 Green-Tomatos, 11.4ms


tensor([102.2246, 115.4147, 162.0208, 149.7925], device='cuda:0')
xyxy:  tensor([568.6878, 464.8248, 618.5953, 527.9257], device='cuda:0')
xyxy:  tensor([130.7638, 177.7244, 193.9386, 240.3035], device='cuda:0')
xyxy:  tensor([802.2366,  89.6366, 848.8459, 143.9189], device='cuda:0')
xyxy:  tensor([ 94.6437, 364.1208, 179.7596, 426.8313], device='cuda:0')
xyxy:  tensor([255.7137, 484.7042, 299.2842, 522.0140], device='cuda:0')
xyxy:  tensor([754.2799, 176.6271, 789.5219, 230.0905], device='cuda:0')
result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[249, 235, 208],
        [234, 220, 193],
        [191, 158, 146],
        ...,
        [110, 117, 123],
        [109, 116, 122],
        [108, 115, 121]],

       [[255, 242, 215],
        [245, 231, 204],
        [200, 167, 155],
 

video 1/1 (27/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 31 Green-Tomatos, 11.4ms
video 1/1 (28/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 27 Green-Tomatos, 11.6ms
video 1/1 (29/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 31 Green-Tomatos, 11.5ms
video 1/1 (30/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 30 Green-Tomatos, 11.5ms
video 1/1 (31/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 12.3ms
video 1/1 (32/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 11.7ms
video 1/1 (33/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 28 Green-Tomatos, 11.3ms


tensor([119.4648, 164.9391, 180.7220, 224.4482], device='cuda:0')
xyxy:  tensor([198.9843, 332.8142, 267.1719, 385.1293], device='cuda:0')
xyxy:  tensor([229.4023, 532.6506, 295.7789, 576.5461], device='cuda:0')
xyxy:  tensor([764.8143, 663.4160, 795.9213, 719.4463], device='cuda:0')
xyxy:  tensor([130.6667, 595.9200, 170.2567, 630.4671], device='cuda:0')
xyxy:  tensor([829.4167, 100.4635, 877.0632, 146.2513], device='cuda:0')
xyxy:  tensor([539.7543, 209.5490, 616.6302, 275.2862], device='cuda:0')
xyxy:  tensor([ 92.7158, 101.6655, 150.0716, 135.9536], device='cuda:0')
xyxy:  tensor([157.5832, 368.9076, 215.2880, 418.1362], device='cuda:0')
xyxy:  tensor([538.5582, 209.4592, 583.8148, 262.2698], device='cuda:0')
xyxy:  tensor([744.9448, 176.8352, 807.7661, 233.8796], device='cuda:0')
xyxy:  tensor([795.6814,  98.6284, 838.7917, 148.7536], device='cuda:0')
xyxy:  tensor([547.6584, 468.9853, 598.4731, 521.3885], device='cuda:0')
xyxy:  tensor([843.4387, 351.6141, 890.5481, 386.2517], de

video 1/1 (34/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 26 Green-Tomatos, 11.5ms
video 1/1 (35/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 26 Green-Tomatos, 11.8ms
video 1/1 (36/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 28 Green-Tomatos, 11.4ms
video 1/1 (37/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 29 Green-Tomatos, 11.5ms
video 1/1 (38/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 33 Green-Tomatos, 11.4ms
video 1/1 (39/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 26 Green-Tomatos, 9.9ms
video 1/1 (40/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 12.1ms


result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[250, 253, 251],
        [250, 253, 251],
        [250, 253, 251],
        ...,
        [255, 255, 249],
        [255, 255, 251],
        [255, 253, 248]],

       [[250, 253, 251],
        [250, 253, 251],
        [250, 253, 251],
        ...,
        [255, 251, 243],
        [255, 251, 246],
        [255, 249, 244]],

       [[250, 253, 251],
        [250, 253, 251],
        [250, 253, 251],
        ...,
        [255, 247, 246],
        [255, 251, 246],
        [255, 253, 248]],

       ...,

       [[224, 203, 216],
        [236, 215, 228],
        [243, 217, 231],
        ...,
        [ 48,  40,  53],
        [ 46,  42,  52],
        [ 41,  37,  47]],

       [[222, 193, 223],
        [237, 208, 238],
        [246, 217, 247

video 1/1 (41/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 26 Green-Tomatos, 11.9ms
video 1/1 (42/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 23 Green-Tomatos, 11.5ms
video 1/1 (43/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 23 Green-Tomatos, 11.5ms
video 1/1 (44/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 12.1ms
video 1/1 (45/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 12.3ms
video 1/1 (46/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 26 Green-Tomatos, 11.5ms
video 1/1 (47/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 11.6ms


tensor([434.4846, 552.2569, 524.9484, 645.3806], device='cuda:0')
xyxy:  tensor([311.6016, 453.1053, 424.3112, 539.2394], device='cuda:0')
xyxy:  tensor([351.7620, 530.8536, 456.9020, 616.1969], device='cuda:0')
xyxy:  tensor([489.4061, 252.2778, 559.7871, 325.0837], device='cuda:0')
xyxy:  tensor([689.4691, 142.9139, 762.1324, 206.3013], device='cuda:0')
xyxy:  tensor([426.7863, 284.5980, 499.0983, 358.2951], device='cuda:0')
xyxy:  tensor([1219.3149,  300.6049, 1279.8091,  373.6117], device='cuda:0')
xyxy:  tensor([1214.6357,  204.2979, 1279.8040,  268.5002], device='cuda:0')
xyxy:  tensor([460.9266, 513.8890, 526.4134, 569.2466], device='cuda:0')
xyxy:  tensor([459.1666,  74.2826, 525.8168, 116.8349], device='cuda:0')
xyxy:  tensor([1224.4258,  492.6911, 1279.6392,  552.2659], device='cuda:0')
xyxy:  tensor([1232.3997,  551.0529, 1279.6243,  625.4583], device='cuda:0')
xyxy:  tensor([2.1479e-01, 4.2092e+02, 5.3242e+01, 4.7570e+02], device='cuda:0')
xyxy:  tensor([420.2247, 215.3547,

video 1/1 (48/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 11.8ms
video 1/1 (49/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 11.5ms
video 1/1 (50/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 23.6ms
video 1/1 (51/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 11.7ms
video 1/1 (52/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 24 Green-Tomatos, 12.1ms
video 1/1 (53/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 11.4ms
video 1/1 (54/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 11.3ms
video 1/1 (55/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 21 Green-Tomatos, 12.4ms


result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[228, 186, 200],
        [220, 178, 192],
        [202, 165, 178],
        ...,
        [138, 132, 140],
        [135, 132, 139],
        [133, 130, 137]],

       [[204, 162, 176],
        [196, 154, 168],
        [184, 147, 160],
        ...,
        [135, 129, 137],
        [132, 129, 136],
        [132, 129, 136]],

       [[182, 145, 163],
        [182, 145, 163],
        [176, 144, 163],
        ...,
        [134, 129, 135],
        [131, 129, 134],
        [131, 129, 134]],

       ...,

       [[ 30,  28,  33],
        [ 30,  28,  33],
        [ 34,  29,  35],
        ...,
        [123, 108, 109],
        [123, 107, 105],
        [122, 106, 104]],

       [[ 30,  27,  34],
        [ 30,  27,  34],
        [ 34,  28,  36

video 1/1 (56/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 23 Green-Tomatos, 12.0ms
video 1/1 (57/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 24 Green-Tomatos, 12.2ms
video 1/1 (58/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 12.4ms
video 1/1 (59/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 26 Green-Tomatos, 11.5ms
video 1/1 (60/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 11.4ms
video 1/1 (61/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 25 Green-Tomatos, 11.8ms
video 1/1 (62/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 11.4ms


result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[210, 201, 235],
        [222, 213, 247],
        [243, 235, 255],
        ...,
        [ 49,  67,  74],
        [ 52,  70,  77],
        [ 54,  72,  79]],

       [[207, 198, 232],
        [217, 208, 242],
        [243, 235, 255],
        ...,
        [ 47,  65,  72],
        [ 49,  67,  74],
        [ 50,  68,  75]],

       [[199, 186, 222],
        [199, 186, 222],
        [218, 207, 230],
        ...,
        [ 47,  66,  70],
        [ 48,  67,  71],
        [ 49,  68,  72]],

       ...,

       [[160, 160, 174],
        [153, 153, 167],
        [147, 147, 161],
        ...,
        [ 21,  23,  25],
        [ 23,  25,  27],
        [ 24,  26,  28]],

       [[158, 159, 169],
        [153, 154, 164],
        [149, 150, 160

video 1/1 (63/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 21 Green-Tomatos, 12.2ms
video 1/1 (64/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 21 Green-Tomatos, 11.5ms
video 1/1 (65/5942) /home/pedrobolsa/Documents/Escola/Investigacao/YoloV8/train/output.mp4: 384x640 22 Green-Tomatos, 12.4ms


tensor([568.6171,  94.6185, 612.5494, 143.6570], device='cuda:0')
xyxy:  tensor([1147.5370,  512.5262, 1227.2484,  562.7705], device='cuda:0')
xyxy:  tensor([580.5111, 366.3361, 612.0209, 413.1711], device='cuda:0')
xyxy:  tensor([1070.9983,  529.2075, 1144.9871,  616.6379], device='cuda:0')
xyxy:  tensor([580.1771, 355.6800, 612.6444, 402.7756], device='cuda:0')
xyxy:  tensor([1058.7683,  281.2240, 1113.9543,  346.4384], device='cuda:0')
result: ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes', 'masks']
masks: ultralytics.yolo.engine.results.Masks object
names: {0: 'Green-Tomato'}
orig_img: array([[[255, 255, 243],
        [255, 255, 246],
        [255, 253, 246],
        ...,
        [ 45,  67,  64],
        [ 42,  64,  61],
        [ 41,  63,  60]],

       [[255, 254, 242],
        [255, 255, 243],
        [255, 251, 244],
        ...,
        [ 46,  68,  65],
        [ 43,  65,  62],

KeyboardInterrupt: 